name: Radar Reflectivity

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update_radar_reflectivity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.18'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib metpy siphon cartopy
    
    - name: Run doppler_radar_Z.py
      run: python doppler_radar_Z.py
    
    - name: Commit and push Reflectivity changes
      run: |
        git config --local user.email "tonyillenden@gmail.com"
        git config --local user.name "anthony-illenden"
        git add plots/radar/Reflectivity_0.png
        git add plots/radar/Reflectivity_1.png
        git add plots/radar/Reflectivity_2.png
        git add plots/radar/Reflectivity_3.png
        git add plots/radar/Reflectivity_4.png
        git add plots/radar/Reflectivity_5.png
        git add plots/radar/Reflectivity_6.png
        git add plots/radar/Reflectivity_7.png
        git add plots/radar/Reflectivity_8.png
        git add plots/radar/Reflectivity_9.png
        git add plots/radar/Reflectivity_10.png
        git add plots/radar/Reflectivity_11.png
        git commit -m "Update Radar Reflectivity Plots"
        git push
