name: Generate NDFD Plan Outputs

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs daily at midnight UTC

jobs:
  generate_high_temp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xarray metpy matplotlib cartopy numpy

    - name: Run ndfd_high_plan.py
      run: python ndfd_high_plan.py
    
    - name: Commit and push High Temp changes
      run: |
        git config --local user.email "tonyillenden@gmail.com"
        git config --local user.name "anthony-illenden"
        git add NDFD_High_Temp_*.png
        git commit -m "Update NDFD High Temp Plot"
        git push

  generate_low_temp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xarray metpy matplotlib cartopy numpy

    - name: Run ndfd_low_plan.py
      run: python ndfd_low_plan.py
    
    - name: Commit and push Low Temp changes
      run: |
        git config --local user.email "tonyillenden@gmail.com"
        git config --local user.name "anthony-illenden"
        git add NDFD_Low_Temp_*.png
        git commit -m "Update NDFD Low Temp Plot"
        git push
